import { Component, signal } from '@angular/core';
import { CounterComponent } from '../counter/counter.component';
import { IsEvenComponent } from '../is-even/is-even.component';
import { MatButtonModule } from '@angular/material/button';
import { ChildComponent } from '../child/child.component';
import { LightboxDirective } from '../lightbox.directive';
import { MyTimerComponent } from '../my-timer/my-timer.component';


@Component({
  selector: 'app-parent',
  standalone: true,
  imports: [CounterComponent, IsEvenComponent, ChildComponent,
     MatButtonModule, LightboxDirective, MyTimerComponent],
  templateUrl: './parent.component.html',
  styleUrl: './parent.component.css'
})
export class ParentComponent {
  count = 0
  myTimer = signal(0)
  public inputValue!: string; // added

  increment() {
    this.count += 1
  }
  decrement() {
    this.count -= 1
  }
  syncProducts(): void {
    // Achieve the operation on trigger of output
    console.log('Trigger from Child using -- output()');
    
  }
  displayTimer($event:any){ // $event is the number generated by the timer comp 
    console.log("Events: ", $event)
    this.myTimer.set($event)
  }
}
